-- Criação da tabela de registro técnico de produtos para agrupamento automático de corte
CREATE TABLE IF NOT EXISTS public.technical_product_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_base TEXT NOT NULL UNIQUE, -- SKU sem variação de tamanho, ex: CAM-DRY-BR
    product_type TEXT, -- Modelo
    fabric TEXT NOT NULL,
    color TEXT NOT NULL,
    tipo_tecido TEXT DEFAULT 'RAMADO',
    largura_util TEXT DEFAULT '1,60 m',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para busca rápida
CREATE INDEX IF NOT EXISTS idx_tech_reg_sku_base ON public.technical_product_registry(sku_base);

-- RLS policies
ALTER TABLE public.technical_product_registry ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all authenticated users" 
ON public.technical_product_registry FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Enable insert access for authenticated users" 
ON public.technical_product_registry FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "Enable update access for authenticated users" 
ON public.technical_product_registry FOR UPDATE 
TO authenticated 
USING (true);
